# @see https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      test-and-build-tooling:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - '@playwright/test'
          - '@quilted/preact-testing'
          - '@quilted/react-testing'
          - '@quilted/rollup'
          - '@quilted/typescript'
          - '@types/node'
          - '@vitest/*'
          - 'jsdom'
          - 'rollup'
          - 'typescript'
          - 'vite'
          - 'vitest'
        update-types:
          - 'minor'
          - 'patch'
      release-tooling:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - '@changesets/*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'prettier'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'changesets/action'
        update-types:
          - 'version-update:semver-major'
