name: Changesets

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    name: Changesets 🦋
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          # This (plus the GITHUB_TOKEN on the changeset action) allow other workflows to run on the PR that changesets creates.
          token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}

      - uses: ./.github/workflows/actions/prepare
      # @see https://github.com/changesets/action
      - uses: changesets/action@198f833dd7d863100ea6e28967bc9a9fdefadb0a # v2.1.0
        with:
          title: 'Publish packages 🚀'
          commit: 'Publish packages'
          version: pnpm version-bump
          publish: pnpm changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
