name: Changesets

on:
  push:
    branches: [main]

permissions: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    name: Changesets 🦋
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/workflows/actions/prepare
      # @see https://github.com/changesets/action
      - uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          # The default GITHUB_TOKEN cannot trigger workflows from release-PR commits.
          github-token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
          title: 'Publish packages 🚀'
          commit: 'Publish packages'
          version: pnpm version-bump
          publish: pnpm changeset tag
