name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks 📝
    uses: ./.github/workflows/checks.yml

  deploy:
    name: Deploy 🚀
    needs: [checks]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write # Required for OIDC authentication
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/workflows/actions/prepare
      - run: pnpm run type-check
      - run: pnpm run build
      - run: pnpm run deploy
        env:
          NPM_TOKEN: '' # Empty string forces OIDC
