name: Preview versions

on:
  workflow_dispatch:
  push:
    branches:
      - changeset-release/main

jobs:
  preview:
    name: Preview 🔮
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/workflows/actions/prepare

      # Changeset entries are consumed on this branch. We need to reset the
      # changeset files so that the snapshot command knows the correct packages,
      # and does not accidentally publish the new, non-preview version numbers
      # prematurely.
      - name: Reset changeset entries
        run: |
          git fetch origin main
          git checkout origin/main -- .changeset

      - run: pnpm run type-check
      - run: pnpm run build

      - name: Deploy preview versions to NPM
        run: |
          pnpm changeset version --snapshot preview
          pnpm changeset publish --tag preview --no-git-tag
        env:
          GITHUB_TOKEN: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
