name: Snapit Remote UI
on:
  issue_comment:
    types:
      - created

jobs:
  snapit:
    name: Snapit Remote UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
          ref: ${{ github.event.comment.user.login == 'github-actions[bot]' && github.event.issue.pull_request.head.ref || github.event.comment.user.login }}

      - uses: actions/setup-node@v4
        name: Setup node.js and yarn
        with:
          cache: yarn
          node-version-file: '.nvmrc'

      - name: Yarn install
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Create snapshot
        uses: Shopify/snapit@main
        env:
          GITHUB_TOKEN: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          build_script: yarn type-check && yarn build
          comment_command: /snapit-remote-ui
